version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flask-test
    volumes:
      - ./src/web:/web
    ports:
      - "5000:5000"

  backend:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flask-test
      - FLASK_APP=hello_world.py
      - PORT=5001
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

    volumes:
      - ./src/backend:/backend
    ports:
      - "5001:5001"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
